### ISSUE TITLE
Implementar modal de edición en detalle.svelte para mejorar la funcionalidad de edición

### ISSUE THREAD

**Issue by moisesnks** [lumonidy-dev/lumo-pos#6]
## Implementación de Modal de Edición en `detalle.svelte`
Necesitamos implementar un modal de edición en `src/lib/pages/main/detalle.svelte` para proporcionar una mejor interfaz de usuario para la funcionalidad de edición de productos. Este modal debe permitir a los usuarios ver y modificar la cantidad del producto seleccionado de manera intuitiva y eficaz.

### Requerimientos específicos:

- [x] **Refactorizar la Función de Edición:** Mejorar la función `editarPedido` en `detalle.svelte` para que, en lugar de su lógica actual, abra un modal de edición.
  
- [x] **Desarrollo del Modal de Edición:** Crear un modal que pueda ser reutilizado en otras partes de la aplicación. Este modal debe incluir:
  - El nombre del producto.
  - La cantidad actual del producto con un input para modificar esta cantidad.
  - Botones para aplicar los cambios o cancelar la edición.

- [x] **Validaciones:** Implementar validaciones para el input de cantidad en el modal (e.g., evitar valores negativos).

- [ ] **Componente Reutilizable:** Considerar el diseño del modal de manera que pueda ser fácilmente reutilizable en otras partes de la aplicación, quizás para otras funcionalidades similares de edición.
e.

### Código de Referencia:
Actualmente, la función `editarPedido` se encuentra así:
```svelte
line 14: function editarPedido(pedido) {
    // todo: Implementar lógica para editar un pedido
}
```
Esta función debe ser modificada para implementar la apertura del nuevo modal de edición.

### Notas Adicionales:
- **Branch de Trabajo:** Por favor, realicen este trabajo en una branch separada llamada `feature/edit-modal`.
- **Componente de Modal:** Consideren crear un body específico para el modal que contenga el nombre del producto y su cantidad, lo cual podría facilitar su reutilización.

**Comment by SmnZin** [comment]
cometi un error, debi haber creado una rama nueva, mala mia para la otra sin falta 🫡
